version: '3'

services:
  pd0:
    image: pingcap/pd:v5.1.1
    container_name: pd0
    hostname: pd0.korov-nas.org
    volumes:
      - ./config/pd.toml:/pd.toml
      - ./pd0_logs:/logs
    command:
      - --config=/pd.toml

  tikv0:
    image: pingcap/tikv:v5.1.1
    container_name: tikv0
    hostname: tikv0.korov-nas.org
    volumes:
      - ./config/tikv.toml:/tikv.toml
      - ./kv0_logs:/logs
    command:
      - --config=/tikv.toml
    depends_on:
      - "pd0"
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #   resources:
    #     limits:
    #       memory: 4G
    #     reservations:
    #       memory: 4G

  tidb:
    image: pingcap/tidb:v5.1.1
    container_name: tidb
    hostname: tidb.korov-nas.org
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml
      - ./tidb_logs:/logs
    command:
      - --config=/tidb.toml
    depends_on:
      - "tikv0"

  pushgateway:
    image: prom/pushgateway:v0.3.1
    command:
      - --log.level=error
    restart: on-failure
  prometheus:
    user: root
    image: prom/prometheus:v2.2.1
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/pd.rules.yml:/etc/prometheus/pd.rules.yml:ro
      - ./config/tikv.rules.yml:/etc/prometheus/tikv.rules.yml:ro
      - ./config/tidb.rules.yml:/etc/prometheus/tidb.rules.yml:ro
    restart: on-failure
  grafana:
    image: grafana/grafana:6.0.1
    user: "0"
    environment:
      GF_LOG_LEVEL: error
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana
      - ./config/dashboards:/tmp/dashboards
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: on-failure 
