= 高级Bash脚本编程指南 =
Korov9 <korov9@163.com>
v1.0 2021-2-17:
:toc: right 

== 初见shell ==

=== 样例-清理日志脚本 ===

[source, BASH]
.cleanup.sh
----
#!/bin/bash
# Cleanup, version 3

# 注意：
# --------
# 此脚本涉及到许多后边才会解释的特性。
# 当你阅读完整本书的一半以后，理解它们就没有任何困难了。


LOG_DIR=/var/log
ROOT_UID=0     # UID为0的用户才拥有root权限。
LINES=50       # 默认保存messages日志文件行数。
E_XCD=86       # 无法切换工作目录的错误码。
E_NOTROOT=87   # 非root权限用户执行的错误码。



# 请使用root权限运行。
if [ "$UID" -ne "$ROOT_UID" ]
then
  echo "Must be root to run this script."
  exit $E_NOTROOT
fi

if [ -n "$1" ]
# 测试命令行参数（保存行数）是否为空
then
  lines=$1
else
  lines=$LINES # 如果为空则使用默认设置
fi


#  Stephane Chazelas 建议使用如下方法检查命令行参数，
#  但是这已经超出了此阶段教程的范围。
#
#    E_WRONGARGS=85  # Non-numerical argument (bad argument format).
#    case "$1" in
#    ""      ) lines=50;;
#    *[!0-9]*) echo "Usage: `basename $0` lines-to-cleanup";
#     exit $E_WRONGARGS;;
#    *       ) lines=$1;;
#    esac
#
#* 在第十一章“循环与分支”中会对此作详细的阐述。


cd $LOG_DIR

if [ `pwd` != "$LOG_DIR" ]  # 也可以这样写 if [ "$PWD" != "$LOG_DIR" ]
                            # 检查工作目录是否为 /var/log ?
then
  echo "Can't change to $LOG_DIR"
  exit $E_XCD
fi  # 在清理日志前，二次确认是否在正确的工作目录下。

# 更高效的写法：
#
# cd /var/log || {
#   echo "Cannot change to necessary directory." >&2
#   exit $E_XCD;
# }


tail -n $lines messages > mesg.temp # 保存messages日志文件最后一部分
mv mesg.temp messages              # 替换系统日志文件以达到清理目的

#  cat /dev/null > messages
#* 我们不需要使用这个方法了，上面的方法更安全

cat /dev/null > wtmp  #  ': > wtmp' 与 '> wtmp' 有同样的效果
echo "Log files cleaned up."
#  注意在/var/log目录下的其他日志文件不会被这个脚本清除

exit 0
#  返回0表示脚本运行成功
----

脚本起始行sha-bang（\#!）告诉系统这个脚本文件需要使用指定的命令解释器来执行。#!实际上是一个占两字节的幻数（magic number）,幻数可以用来标识特殊的文件类型，在这里则是标记可执行shell脚本（你可以在终端中输入man magic了解更多信息）。紧随#!的是一个路径名。此路径指向用来解释此脚本的程序，它可以是shell，可以是程序设计语言，也可以是实用程序。这个解释器从头（#!的下一行）开始执行整个脚本的命令，同时忽略注释。

----
#!/bin/sh
#!/bin/bash
#!/usr/bin/perl
#!/usr/bin/tcl
#!/bin/sed -f
#!/bin/awk -f
----

上面每一条脚本起始行都调用了不同的解释器，比如 `/bin/sh` 调用了系统默认shell（Linux系统中默认是bash）。大部分UNIX商业发行版中默认的是Bourne shell，即 `#!/bin/sh` 。你可以以牺牲Bash特性为代价，在非Linux的机器上运行sh脚本。当然，脚本得遵循POSIX sh标准。

当脚本仅包含一些通用的系统命令而不使用shell内部指令时，可以省略 `\#!` 。第三个例子需要#!是因为当对变量赋值时，例如 `lines=50` ，使用了与shell特性相关的结构。再重复一次， `#!/bin/sh` 调用的是系统默认shell解释器，在Linux系统中默认为 `/bin/bash` 。

=== 样例：自我删除脚本 ===

[source, BASH]
----
#!/bin/rm
# 自我删除的脚本

# 当你运行这个脚本，除了这个脚本本身消失以外并不会发生什么。

WHATEVER=85

echo "This line will never print (betcha!)."

exit $WHATEVER  # 这没有任何关系。脚本将不会从这里退出。
                # 尝试在脚本终止后打印echo $a。
                # 得到的值将会是0而不是85.
----

=== 调用一个脚本 ===

写完一个脚本以后，你可以通过 `sh scriptname` 或 `bash scriptname` 来调用它(不推荐使用 `sh scriptname` 调用脚本，因为这会禁用脚本从标准输入（ `stdin` ）读入数据)

== 部分shell基础 ==

=== 特殊字符 ===

`#`

注释符。如果一行脚本的开头是#（除了#!），那么代表这一行是注释，不会被执行。

`;`

命令分隔符[分号]。允许在同一行内放置两条或更多的命令。注意有时候";"需要被转义才能正常工作。

[source, BASH]
----
echo hello; echo there

if [ -x "$filename" ]; then    #  注意在分号以后有一个空格
#+                   ^^
  echo "File $filename exists."; cp $filename $filename.bak
else   #                       ^^
  echo "File $filename not found."; touch $filename
fi; echo "File test complete."
----

`;;`

`case` 条件语句终止符[双分号]。

[source, BASH]
----
case "$variable" in
  abc)  echo "\$variable = abc" ;;
  xyz)  echo "\$variable = xyz" ;;
esac
----

`;;&, ;&`

case条件语句终止符（Bash4+ 版本）。

`"`

部分引用[双引号]。在字符串中保留大部分特殊字符。

`'`

全引用[单引号]。在字符串中保留所有的特殊字符。是部分引用的强化版。

`,`

[source,BASH]
----
let "t2 = ((a = 9, 15 / 3))"
# a被赋值为9，t2被赋值为15 / 3
----

逗号运算符也可以用来连接字符串。

[source,BASH]
----
for file in /{,usr/}bin/*calc
#             ^    在 /bin 与 /usr/bin 目录中
#+                 找到所有的以"calc"结尾的可执行文件
do
        if [ -x "$file" ]
        then
          echo $file
        fi
done

# /bin/ipcalc
# /usr/bin/kcalc
# /usr/bin/oidcalc
# /usr/bin/oocalc

# 感谢Rory Winston提供的执行结果
----

`,, ,`

在参数替换中进行小写字母转换（Bash4 新增）。

`\`

转义符[反斜杠]。转义某字符的标志。
\x转义了字符x。双引号""内的X与单引号内的X具有同样的效果。 转义符也可以用来转义"与'，使它们表达其字面含义。

`/`

文件路径分隔符[正斜杠]。起分割路径的作用。（比如 `/home/bozo/projects/Makefile`）
它也在算术运算中充当除法运算符。

`

命令替换符。` command ` 结构可以使得命令的输出结果赋值给一个变量。通常也被称作后引号（backquotes）或反引号（backticks）。

`:`

空命令[冒号]。它在shell中等价于"NOP"（即no op，空操作）与shell内建命令true有同样的效果。它本身也是Bash的内建命令之一，返回值是true（0）。

[source,BASH]
----
:
echo $?   # 返回0

: ${username=`whoami`}
# ${username=`whoami`}   如果没有:就会报错
#                        除非 "username" 是系统命令或内建命令

: ${1?"Usage: $0 ARGUMENT"}     # 摘自样例脚本 "usage-message.sh"


: ${HOSTNAME?} ${USER?} ${MAIL?}
#  如果其中一个或多个必要的环境变量没有被设置
#  将会打印错误


# 与>重定向操作符结合，可以在不改变文件权限的情况下清空文件。如果文件不存在，那么将创建这个文件。
: > data.xxx   # 文件 "data.xxx" 已被清空
# 与>>重定向操作符结合，将不会清空任何已存在的文件（: >> target_file）。如果文件不存在，将创建这个文件。
----

`!`

取反（或否定）操作符[感叹号]。! 操作符反转已执行的命令的返回状态（查看样例 6-2）。它同时可以反转测试操作符的意义，例如可以将相等（=）反转成不等（!=）。它是一个Bash关键词。

`?`

测试操作符[问号]。在一些特定的语句中，? 表示一个条件测试。
在一个双圆括号结构中，? 可以表示一个类似C语言风格的三元（trinary）运算符的一个组成部分。
[source,BASH]
----
(( var0 = var1<98?9:21 ))
#不要加空格，紧挨着写

#等价于
# if [ "$var1" -lt 98 ]
# then
#   var0=9
# else
#   var0=21
# fi
----

`$`

取值符号[钱字符]，用来进行变量替换（即取出变量的内容）。
[source,BASH]
----
var1=5
var2=23skidoo

echo $var1     # 5
echo $var2     # 23skidoo
----

`$$`

进程ID变量。此变量保存该运行脚本的进程ID。

`()`

命令组，`(a=hello; echo $a)` 

[NOTE]
通过括号执行一系列命令会产生一个子shell（subshell）。 括号中的变量，即在子shell中的变量，在脚本的其他部分是不可见的。父进程脚本不能访问子进程（子shell）所创建的变量。
[source,BASH]
----
a=123
( a=321; )

echo "a = $a"   # a = 123
# 在括号中的 "a" 就像个局部变量。
----

数组初始化。
[source,BASH]
----
Array=(element1 element2 element3)
----

`{xxx,yyy,zzz,...}`

花括号扩展结构
[source,BASH]
----
echo \"{These,words,are,quoted}\"   # " 将作为单词的前缀和后缀
# "These" "words" "are" "quoted"


cat {file1,file2,file3} > combined_file
# 将 file1, file2 与 file3 拼接在一起后写入 combined_file 中。

cp file22.{txt,backup}
# 将 "file22.txt" 拷贝为 "file22.backup"

echo {file1,file2}\ :{\ A," B",' C'}
file1 : A file1 : B file1 : C file2 : A file2 : B file2 : C
----

`{a..z}`

扩展的花括号扩展结构。
[source,BASH]
----
echo {a..z} #  a b c d e f g h i j k l m n o p q r s t u v w x y z
# 输出 a 到 z 之间所有的字母。

echo {0..3} # 0 1 2 3
# 输出 0 到 3 之间所有的数字。


base64_charset=( {A..Z} {a..z} {0..9} + / = )
# 使用扩展花括号初始化一个数组。
# 摘自 vladz 编写的样例脚本 "base64.sh"。
----









`/`

文件路径分隔符[正斜杠]。起分割路径的作用。（比如 `/home/bozo/projects/Makefile`）
它也在算术运算中充当除法运算符。

`\``

