server:
  port: 8006

spring:
  application:
    name: fastdfs-demo


# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个
    - 192.168.31.84:22122
    #- 192.168.8.102:22122