version: '3.4'

services: 
    elasticsearch:
        image: elastic/elasticsearch:7.15.2
        container_name: elasticsearch
        ports: 
            - 9200:9200
            - 9300:9300
        environment: 
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
          # chown -R 1000 /share/docker/elk
          - "/share/docker/elk/elasticsearch/conf/elasticsearch.yml::/usr/share/elasticsearch/config/elasticsearch.yml:rw"
          - "/share/docker/elk/elasticsearch/data:/usr/share/elasticsearch/data:rw"
        hostname: elasticsearch.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.12
    logstash:
        image: elastic/logstash:7.15.2
        container_name: logstash
        volumes: 
            - "/share/docker/elk/logstash/patterns:/usr/share/logstash/patterns:rw"
            - "/share/docker/elk/logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:rw"
        ports: 
            - "5044:5044"
            - "9600:9600"
        environment: 
            - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
        depends_on: 
            - elasticsearch
        hostname: logstash.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.13
    kibana:
        image: elastic/kibana:7.15.2
        container_name: kibana
        volumes: 
            - "/share/docker/elk/kibana/conf/kibana.yaml:/usr/share/kibana/config/kibana.yml:rw"
        ports: 
            - 5601:5601
        depends_on: 
            - elasticsearch
        hostname: kibana.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.14

networks:
   net_korov:
    external:
      name: korov-nas