version: "3"
services:
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:6.1.0
    environment:
      - MM_USERNAME=mattermost
      - MM_PASSWORD=mattermost
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgres.korov-nas.org:5432/mattermost?sslmode=disable&connect_timeout=10
    volumes:
      # chown -R 2000:2000 /share/docker/mattermost
      - /share/docker/mattermost/config:/mattermost/config:rw
      - /share/docker/mattermost/data:/mattermost/data:rw
      - /share/docker/mattermost/logs:/mattermost/logs:rw
      - /share/docker/mattermost/plugins:/mattermost/plugins:rw
      - /share/docker/mattermost/client/plugins:/mattermost/client/plugins:rw
    ports:
      - "8065:8065"
    hostname: mattermost.korov-nas.org
    networks:
      net_korov:
        ipv4_address: 172.19.0.8

networks:
   net_korov:
    external:
      name: korov-nas
