version: "3.8"
services:
  zookeeper:
    container_name: zookeeper-flink
    image: zookeeper:3.5.8
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-flink
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    links:
      - zookeeper:zookeeper

  mongo:
    container_name: mongo-flink
    image: mongo:4.4.5
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"

  jobmanager:
    image: flink:1.12.2-scala_2.12-java11
    container_name: flink-jobmanager-flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
  taskmanager:
    image: flink:1.12.2-scala_2.12-java11
    container_name: flink-taskmanager-flink
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    depends_on:
      - jobmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4

  postgres:
    image: postgres:12.4
    container_name: postgres-flink
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
