version: "3"
services:
  kafka:
    container_name: kafka-flink
    image: bitnami/kafka:3.3.2
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.50.100:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  mongo:
    container_name: mongo-flink
    image: mongo:6.0.4
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - /data/mongo/db:/data/db

  jobmanager:
    image: flink:1.16.1
    container_name: flink-jobmanager-flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
        rest.flamegraph.enabled: true
        state.savepoints.dir: file:////opt/flink/savepoints
  taskmanager:
    image: flink:1.16.1
    container_name: flink-taskmanager-flink
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    depends_on:
      - jobmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
        taskmanager.numberOfTaskSlots: 8
        rest.flamegraph.enabled: true
        state.savepoints.dir: file:////opt/flink/savepoints
