seata:
  enabled: true
  enable-auto-data-source-proxy: true
#  config:
#    type: nacos
#    nacos:
#      server-addr: korov.linux.org:8848
#      username: nacos
#      password: nacos
#  registry:
#    type: nacos
#    nacos:
#      server-addr: korov.linux.org:8848
#      username: nacos
#      password: nacos
spring:
  application:
    name: distributation_transication
  datasource:
    url: jdbc:mysql://korov.linux.org:3306/test?allowMultiQueries=true&jdbcCompliantTruncation=false&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123

nacos:
  config:
    server-addr: korov.linux.org:8848
    username: nacos
    password: nacos
  discovery:
    server-addr: korov.linux.org:8848
    username: nacos
    password: nacos