server:
  port: 8002


mybatis:
  type-aliases-package: com.distributed.lock.mysql.model    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/*.xml                       # mapper映射文件

spring:
  application:
    name: redis-demo
  redis:
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      nodes:
        - localhost:6061
        - localhost:6062
        - localhost:6063
        - localhost:6064
        - localhost:6065
        - localhost:6066
    jedis:
      pool:
        max-idle: 300
        max-wait: 1000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/lock_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true            # 数据库名称
    username: root
    password: root123
