version: "3"
services:
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:5.35
    environment:
      - MM_USERNAME=mattermost
      - MM_PASSWORD=mattermost
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgres.korov-nas.org:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - "8065:8065"
    hostname: mattermost.korov-nas.org
    networks:
      net_korov:
        ipv4_address: 172.19.0.7

networks:
   net_korov:
    external:
      name: korov-nas
