spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/rolemanager?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true            # 数据库名称
    username: root
    password: root123

info:
  app.name: provider-user
  app.author: korovs
