version: "3"
services:
  arango-standalone:
    image: arangodb/arangodb:3.7.2
    container_name: arango-standalone
    hostname: arango-standalone
    ports: 
      - "8528:8529"
    volumes:
      - $PWD/arango-standalone/config:/var/lib/arangodb3/config
      - $PWD/arango-standalone/dbserver:/var/lib/arangodb3/dbserver
    command: /bin/sh -c "arangod -c /var/lib/arangodb3/config/arangodb.conf"

  arango-cluster-single:
    image: arangodb/arangodb:3.7.2
    container_name: arango-cluster-single
    hostname: arango-cluster-single
    ports: 
      - "8529:8529"
    volumes:
      - $PWD/arango-cluster-single/config:/var/lib/arangodb3/config
      - $PWD/arango-cluster-single/agency:/var/lib/arangodb3/agency
      - $PWD/arango-cluster-single/dbserver:/var/lib/arangodb3/dbserver
      - $PWD/arango-cluster-single/coordinator:/var/lib/arangodb3/coordinator
    command: /bin/sh -c "/usr/sbin/arangod -c /var/lib/arangodb3/config/agent.conf & /usr/sbin/arangod -c /var/lib/arangodb3/config/arangodb.conf & /usr/sbin/arangod -c /var/lib/arangodb3/config/coordinator.conf"

  arango-cluster-server1:
    image: arangodb/arangodb:3.7.2
    container_name: arango-cluster-server1
    hostname: arango-cluster-server1
    ports: 
      - "8530:8529"
    volumes:
      - $PWD/arango-cluster-server1/config:/var/lib/arangodb3/config
      - $PWD/arango-cluster-server1/agency:/var/lib/arangodb3/agency
      - $PWD/arango-cluster-server1/dbserver:/var/lib/arangodb3/dbserver
      - $PWD/arango-cluster-server1/coordinator:/var/lib/arangodb3/coordinator
    command: /bin/sh -c "arangod -c /var/lib/arangodb3/config/agent.conf & arangod -c /var/lib/arangodb3/config/arangodb.conf & arangod -c /var/lib/arangodb3/config/coordinator.conf"
    
  arango-cluster-server2:
    image: arangodb/arangodb:3.7.2
    container_name: arango-cluster-server2
    hostname: arango-cluster-server2
    ports: 
      - "8531:8529"
    volumes:
      - $PWD/arango-cluster-server2/config:/var/lib/arangodb3/config
      - $PWD/arango-cluster-server2/agency:/var/lib/arangodb3/agency
      - $PWD/arango-cluster-server2/dbserver:/var/lib/arangodb3/dbserver
      - $PWD/arango-cluster-server2/coordinator:/var/lib/arangodb3/coordinator
    command: /bin/sh -c "arangod -c /var/lib/arangodb3/config/agent.conf & arangod -c /var/lib/arangodb3/config/arangodb.conf & arangod -c /var/lib/arangodb3/config/coordinator.conf"

  arango-cluster-server3:
    image: arangodb/arangodb:3.7.2
    container_name: arango-cluster-server3
    hostname: arango-cluster-server3
    ports: 
      - "8532:8529"
    volumes:
      - $PWD/arango-cluster-server3/config:/var/lib/arangodb3/config
      - $PWD/arango-cluster-server3/agency:/var/lib/arangodb3/agency
      - $PWD/arango-cluster-server3/dbserver:/var/lib/arangodb3/dbserver
      - $PWD/arango-cluster-server3/coordinator:/var/lib/arangodb3/coordinator
    command: /bin/sh -c "arangod -c /var/lib/arangodb3/config/agent.conf & arangod -c /var/lib/arangodb3/config/arangodb.conf & arangod -c /var/lib/arangodb3/config/coordinator.conf"
