server:
  port: 8080
spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowledge?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root123
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化，最小，最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 18
      # 获取数据库连接等待的超时时间
      max-wait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM dual
      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat,wall,slf4j
      ##监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
        profile-enable: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置默认false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        # ip黑白名单
        allow: 127.0.0.1
        deny:


#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml #mapper文件路径
  type-aliases-package: com.korov.gradle.knowledge.model   #来指明和数据库映射的实体的所在包。
