version: '3'

services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    hostname: influxdb.korov-nas.org
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=zl7636012086
      - DOCKER_INFLUXDB_INIT_ORG=korov
      - DOCKER_INFLUXDB_INIT_BUCKET=korov
    ports:
      - "8086:8086"
    volumes:
      - /share/docker/influxdb/data:/var/lib/influxdb2
      - /share/docker/influxdb/config.yml:/etc/influxdb2/config.yml
    networks:
      net_korov:
        ipv4_address: 172.19.0.15

networks:
   net_korov:
    external:
      name: korov-nas
