version: '3'

services: 
    mysql:
        image: mysql:8.0.27
        container_name: mysql
        ports: 
          - "3306:3306"
        environment: 
          - MYSQL_ROOT_PASSWORD=zl7636012086
        volumes:
          - /share/docker/mysql/data:/var/lib/mysql
          - /share/docker/mysql/conf:/etc/mysql/conf.d
          - /share/docker/mysql/log:/var/log/mysql
        hostname: mysql.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.5

networks:
   net_korov:
    external:
      name: korov-nas