version: '3'

services: 
    postgres:
        image: postgres:14.1
        container_name: postgres
        ports: 
            - "5432:5432"
        environment: 
            - "POSTGRES_PASSWORD=zl7636012086"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
          - "/share/docker/postgres/data:/var/lib/postgresql/data"
        hostname: postgres.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.4

networks:
   net_korov:
    external:
      name: korov-nas