version: '3'

services: 
    redis:
        image: redis:6.2.6
        container_name: redis
        ports: 
          - "6379:6379"
        volumes:
          - /share/docker/redis/data:/data
          - /share/docker/redis/config/users.acl:/etc/users.acl
          - /share/docker/redis/config/redis.conf:/etc/redis.conf
          - /share/docker/redis/logs:/logs
        command:
          redis-server /etc/redis.conf
        deploy:
            resources:
                limits:
                    memory: 1024M
                reservations:
                    memory: 256M
        hostname: redis.korov-nas.org
        networks:
          net_korov:
            ipv4_address: 172.19.0.3

networks:
   net_korov:
    external:
      name: korov-nas