= java log日志框架介绍 =
Korov9 <korov9@163.com>
v1.0 2020-12-20
:toc: right

== log4j ==

示例
[source, properties]
.log4j.properties
----
log4j.rootCategory=INFO,stdout,R

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[QC] %p [%t] %C.%M(%L) | %m%n
 
log4j.appender.R=org.apache.log4j.DailyRollingFileAppender
log4j.appender.R.File=D:\\Tomcat 5.5\\logs\\qc.log
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d-[TS] %p %t %c - %m%n

# 指定com.neusoft包下的所有类的等级为DEBUG。
log4j.logger.com.neusoft=DEBUG
log4j.logger.com.opensymphony.oscache=ERROR
----

. `log4j.rootCategory=INFO,stdout,R` :此句为将等级为INFO的日志信息输出到stdout和R这两个目的地，stdout和R的定义在下面的代码，可以任意起名。等级可分为OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL，如果配置OFF则不打出任何信息，如果配置为INFO这样只显示INFO、WARN、ERROR的log信息，而DEBUG信息不会被显示

. `log4j.appender.stdout=org.apache.log4j.ConsoleAppender` :此句为定义名为stdout的输出端是哪种类型，可以是org.apache.log4j.ConsoleAppender（控制台），org.apache.log4j.FileAppender（文件），org.apache.log4j.DailyRollingFileAppender（每天产生一个日志文件），org.apache.log4j.RollingFileAppender（文件大小到达指定尺寸的时候产生一个新的文件）org.apache.log4j.WriterAppender（将日志信息以流格式发送到任意指定的地方）

. `log4j.appender.stdout.layout=org.apache.log4j.PatternLayout` :此句为定义名为stdout的输出端的layout是哪种类型，可以是org.apache.log4j.HTMLLayout（以HTML表格形式布局），org.apache.log4j.PatternLayout（可以灵活地指定布局模式），org.apache.log4j.SimpleLayout（包含日志信息的级别和信息字符串），org.apache.log4j.TTCCLayout（包含日志产生的时间、线程、类别等等信息）

. `log4j.appender.stdout.layout.ConversionPattern= [QC] %p [%t] %C.%M(%L) | %m%n` :如果使用pattern布局就要指定的打印信息的具体格式ConversionPattern，打印参数如下：
%m 输出代码中指定的消息；
%M 输出打印该条日志的方法名；
%p 输出优先级，即DEBUG，INFO，WARN，ERROR，FATAL；
%r 输出自应用启动到输出该log信息耗费的毫秒数；
%c 输出所属的类目，通常就是所在类的全名；
%t 输出产生该日志事件的线程名；
%n 输出一个回车换行符，Windows平台为"rn”，Unix平台为"n”；
%d 输出日志时间点的日期或时间，默认格式为ISO8601，也可以在其后指定格式，比如：%d{yyyy-MM-dd HH:mm:ss,SSS}，输出类似：2002-10-18 22:10:28,921；
%l 输出日志事件的发生位置，及在代码中的行数；
[QC]是log信息的开头，可以为任意字符，一般为项目简称。
输出的信息
[TS] DEBUG [main] AbstractBeanFactory.getBean(189) | Returning cached instance of singleton bean 'MyAutoProxy'

=== 定义配置文件 ===

log4j支持两种配置文件格式，一种时xml一种时properties。

. 配置根Logger：Logger负责处理日志记录的大部分操作，其语法为：`log4j.rootLogger = [ level ] , appenderName, appenderName, …`
. 配置日志信息输出目的地Appender：Appender负责控制日志记录操作的输出。其语法为

[source, properties]
.log4j.properties
----
log4j.appender.appenderName = fully.qualified.name.of.appender.class
log4j.appender.appenderName.option1 = value1
----

== log4j2配置详解 ==

=== 配置文件节点详解 ===

==== 根节点 ====

根节点有两个属性 `status` 和 `monitorinterval`，有两个子节点： `Appenders` 和 `Loggers` (可以定义多个 `Apender` 和 `Logger`)。 `status` 用来指定 `log4j` 本身的打印日志级别。 `monitorinterval` 用来指定 `log4j` 自动重新配置的监测间隔事件，单位时秒，最小5秒(定时监测配置文件，按照最新的配置文件执行)。

==== Appenders节点 ====

`Appenders` 节点，常见有三种子节点： `Console`, `RollingFile`, `File`。

. `Console`:定义输出到控制台的 `Appender`， `_name_` 指定 `Appender` 的名字，`_target_`（ `SYSTEM_OUT` 或  `SYSTEM_ERR` ）默认 `SYSTEM_OUT`， `_PatternLayout_` 输出格式默认 `%m%n`

. `File`:定义输出日志到指定位置的文件的 `Appender`。 `_name_`指定 `Appender` 的名字， `_fileName_`：指定输出日志的目的文件带全路径的文件名， `_PatternLayout_` 输出格式默认 `%m%n`

. `RollingFile` :用来定义超过滚动更新文件的 `Appender`。 `_name_` 指定 `Appender` 的名字， `_fileName_`：指定输出日志的文件带全路径的文件名， `_PatternLayout_` 输出格式默认 `%m%n`， `_filePattern_`:指定新建日志文件的名称格式， `_Policies_`:指定滚动日志的策略，就是什么时候进行新建日志文件输出日志， `_TimeBasedTriggeringPolicy_` : `Policies` 子节点，基于事件的滚动策略， `interval` 属性用来指定多久滚动一次，默认1小时， `modulate=true` 用来调整时间(比如当前时早上3am，interval是4，那么第一次滚动是在4am
，8am，12am... 而不是7am)， `_SizeBasedTriggeringPolicy_`: `Policies` 子节点，基于指定文件大小的滚动策略， `size` 属性用来定义每个日志文件的大小， `_DefaultRolloverStrategy_` :用来指定同一个文件夹下最多有几个日志文件时开始删除最旧的，创建新的通过 `max` 属性确认，默认是7个文件


==== Loggers节点 ====

常见的有两种 `Root` 和 `Logger`

`Root` 节点用来指定项目的根日志，如果没有单独指定Logger，那么就会默认使用该Root日志输出。 `_level_` :日志输出级别，共8个级别 `All < Trace < Debug < Info < Warn < Error < Fatal < OFF`, `_AppenderRef_` ：Root的子节点，用来指定该日志输出到哪个 Appender

`Logger`节点用来单独指定日志的形式，比如要为指定包下的class指定不同的日志级别等。`_level_` :日志输出级别，共8个级别 `All < Trace < Debug < Info < Warn < Error < Fatal < OFF`, `_AppenderRef_` ：Logger的子节点，用来指定该日志输出到哪个Appender,如果没有指定，就会默认继承自Root.如果指定了，那么会在指定的这个Appender和Root的Appender中都会输出，此时我们可以设置Logger的additivity="false"只在自定义的Appender中进行输出。， `_name_` :用来指定该Logger所适用的类或者类所在的包的全路径，继承自Root节点。

=== 输出格式详解 ===

=== demo ===

[source, xml]
.log4j2.xml
----
<?xml version="1.0" encoding="UTF-8"?>
 <!--Configuration后面的status，这个用于设置log4j2自身内部的信息输出，可以不设置-->
 <!--monitorInterval：Log4j能够自动检测修改配置 文件和重新配置本身，设置间隔秒数-->
 <configuration status="WARN" monitorInterval="30">
    <!--先定义所有的appender-->
     <appenders>
		<!--输出到控制台-->
         <console name="Console" target="SYSTEM_OUT">
         <!--输出日志的格式-->
             <PatternLayout pattern="[%d{HH:mm:ss:SSS}] [%p] - %l - %m%n"/>
         </console>
		<!--打印到文件中，这个log每次运行程序会自动清空，由append属性决定-->
		<File name="log" fileName="log/test.log" append="false">
			<PatternLayout pattern="%d{HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"/>
		 </File>
		<!--文件滚动, 这个会打印出所有的info及以下级别的信息，每次大小超过size，则这size大小的日志会自动存入按年份-月份建立的文件夹下面并进行压缩，作为存档-->
         <RollingFile name="RollingFileInfo" fileName="${sys:user.home}/logs/info.log"
                      filePattern="${sys:user.home}/logs/$${date:yyyy-MM}/info-%d{yyyy-MM-dd}-%i.log">
             <!--控制台只输出level及以上级别的信息（onMatch），其他的直接拒绝（onMismatch）-->        
             <ThresholdFilter level="info" onMatch="ACCEPT" onMismatch="DENY"/>
             <PatternLayout pattern="[%d{HH:mm:ss:SSS}] [%p] - %l - %m%n"/>
             <Policies>
				 <DefaultRolloverStrategy max="20"/>   <!--文件夹下最多的文件个数-->
                 <TimeBasedTriggeringPolicy interval="2 hour"/>			<!--多长时间滚动一次-->
                 <SizeBasedTriggeringPolicy size="100 MB"/>		<!-- 一个日志文件的最大大小 -->
             </Policies>
         </RollingFile>
        
         
     </appenders>
     <!--然后定义logger，只有定义了logger并引入的appender，appender才会生效-->
     <loggers>
         <!--过滤掉spring和mybatis的一些无用的DEBUG信息-->
        <logger name="org.springframework" level="INFO"></logger>
         <logger name="org.mybatis" level="INFO"></logger>
         <root level="all">		 
            <appender-ref ref="Console"/>
             <appender-ref ref="RollingFileInfo"/>
             <appender-ref ref="RollingFileWarn"/>
             <appender-ref ref="RollingFileError"/>
         </root>
     </loggers>
 </configuration>
----

== logback ==

和log4j2相似的配置，定义好Appender，然后定义Logger指向指定的Appender

[source, xml]
.logback.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">

    <!--定义日志文件的存储地址 勿在 LogBack 的配置中使用相对路径-->
    <property name="LOG_HOME" value="/home" />

    <!--控制台日志， 控制台输出 -->
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <!--格式化输出：%d表示日期，%thread表示线程名，%-5level：级别从左显示5个字符宽度,%msg：日志消息，%n是换行符-->
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
        </encoder>
    </appender>

    <!--文件日志， 按照每天生成日志文件 -->
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!--日志文件输出的文件名-->
            <FileNamePattern>${LOG_HOME}/TestWeb.log.%d{yyyy-MM-dd}.log</FileNamePattern>
            <!--日志文件保留天数-->
            <MaxHistory>30</MaxHistory>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <!--格式化输出：%d表示日期，%thread表示线程名，%-5level：级别从左显示5个字符宽度%msg：日志消息，%n是换行符-->
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
        </encoder>
        <!--日志文件最大的大小-->
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <MaxFileSize>10MB</MaxFileSize>
        </triggeringPolicy>
    </appender>

    <!-- show parameters for hibernate sql 专为 Hibernate 定制 -->
    <logger name="org.hibernate.type.descriptor.sql.BasicBinder" level="TRACE" />
    <logger name="org.hibernate.type.descriptor.sql.BasicExtractor" level="DEBUG" />
    <logger name="org.hibernate.SQL" level="DEBUG" />
    <logger name="org.hibernate.engine.QueryParameters" level="DEBUG" />
    <logger name="org.hibernate.engine.query.HQLQueryPlan" level="DEBUG" />

    <!--myibatis log configure-->
    <logger name="com.apache.ibatis" level="TRACE"/>
    <logger name="java.sql.Connection" level="DEBUG"/>
    <logger name="java.sql.Statement" level="DEBUG"/>
    <logger name="java.sql.PreparedStatement" level="DEBUG"/>

    <!-- 日志输出级别 -->
    <root level="DEBUG">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="FILE"/>
    </root>
</configuration>
----