version: 3

services:
  mysql:
    container_name: security_mysql
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=security"
      - "MYSQL_PASSWORD=security"
      - "MYSQL_DATABASE=security"
