server:
  port: 8085

logging:
  config: classpath:logback.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowMultiQueries=true&jdbcCompliantTruncation=false&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
    username: security
    password: security
  application:
    name: security

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/test