version: "3.8"
services: 
    zookeeper:
      container_name: zookeeper
      image: zookeeper:3.5.8
      ports:
        - "2181:2181"

    kafka:
      container_name: kafka
      image: wurstmeister/kafka:2.13-2.6.0
      expose:
        - 9999
      ports:
        - 9092:9092
        - 9999:9999
      environment:
        KAFKA_ADVERTISED_LISTENERS: OUTSIDE://korov-linux.org:9092
        KAFKA_LISTENERS: OUTSIDE://:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "test:1:1"
        JMX_PORT: 9999
      links:
        - zookeeper:zookeeper
