version: '3.4'

services: 
    elasticsearch:
        image: elastic/elasticsearch:7.15.2
        container_name: elasticsearch
        ports: 
            - 9200:9200
            - 9300:9300
        environment: 
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logstash:
        image: elastic/logstash:7.15.2
        container_name: logstash
        volumes: 
            - "./siem_pattern:/usr/share/logstash/patterns/siem_pattern:ro"
            - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
        ports: 
            - "5044:5044"
            - "9600:9600"
        environment: 
            - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
        depends_on: 
            - elasticsearch
    kibana:
        image: elastic/kibana:7.15.2
        container_name: kibana
        volumes: 
            - "./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro"
        ports: 
            - 5601:5601
        depends_on: 
            - elasticsearch