server:
  port: 8101

#Development Environment
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  application:
    name: rolemanager-consumer
  rabbitmq:
    host: 192.168.106.143
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,info,hystrix.stream

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.106.141:7001/eureka
  instance:
    instance-id: rolemanager-consumer-8101
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: provider-user
  app.author: korovs