server:
  port: 4001

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  application:
    name: rolemanager-gateway
  rabbitmq:
    host: 192.168.106.143
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      #关闭cros
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: route-consumer
          uri: lb://rolemanager-consumer
          predicates:
            - Path=/gateway/**
          filters:
            #- RewritePath=/CONSUMER/(?<segment>.*), /$\{segment}
            - StripPrefix=1 #从前面截取一个，实际上就是截取url，本例中就是会把/gateway截掉，后面的部分才是转发的url
      discovery:
        locator:
          lower-case-service-id: true  #转发的时候可以使用小写的服务名称
          enabled: true #与服务发现组件结合，通过serviceId转发到具体的服务实例


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,info,hystrix.stream

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.106.141:7001/eureka
  instance:
    instance-id: rolemanager-gateway-4001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: provider-user
  app.author: korovs
