server:
  port: 80010

#Development Environment
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

mybatis:
  type-aliases-package: com.korov.cloud.rolemanager.provider    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*Mapper.xml                       # mapper映射文件

spring:
  application:
    name: rolemanager-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://192.168.106.143:3306/RoleManager?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true            # 数据库名称
    username: root
    password: root123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 50                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  rabbitmq:
    host: 192.168.106.143
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: 192.168.106.143
      port: 27017
      database: test
  redis:
    database: 0
    host: 192.168.106.143
    port: 6379
    password:
    timeout: 1000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 10
      min-idle: 0

management:
  endpoints:
    health:
      show-details: always  #总是显示详细信息
    web:
      exposure:
        include: bus-refresh,info,hystrix.stream  #表示打开相应的端点

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://192.168.106.141:7001/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: rolemanager-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: provider-user
  app.author: korovs
