server:
  port: 8002

spring:
  application:
    name: redis-demo
  redis:
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      nodes:
        - localhost:6061
        - localhost:6062
        - localhost:6063
        - localhost:6064
        - localhost:6065
        - localhost:6066
    jedis:
      pool:
        max-idle: 300
        max-wait: 1000
