DELIMITER $$

DROP PROCEDURE IF EXISTS DEMO_SQUARE $$

CREATE PROCEDURE DEMO_SQUARE(OUT DEMO_RESULT VARCHAR(1024))
LAB_DEMO_SQUARE:
BEGIN
    DECLARE V_ID INT DEFAULT 0;
    DECLARE V_TEMP INT DEFAULT 0;
    DECLARE V_TEMP1 INT DEFAULT 0;
    DECLARE DONE INT DEFAULT 0;
    DECLARE DUPLICATE_KEY CONDITION FOR 1062;
    DECLARE CURSOR_SQUARE CURSOR FOR
    SELECT ID,DEFAULT_VALUE FROM TBL_VALUE_TEMP;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done=1;
    DECLARE CONTINUE HANDLER FOR DUPLICATE_KEY
    BEGIN
        SET DEMO_RESULT='Duplicate key error';
    END;
    
    OPEN CURSOR_SQUARE;
    REPEAT
        FETCH CURSOR_SQUARE INTO V_ID,V_TEMP;
        UPDATE TBL_VALUE_TEMP SET `VALUE`=POW(V_TEMP,2) WHERE ID=V_ID;
        -- 抑制select输出
        SELECT ID INTO V_TEMP1 FROM TBL_VALUE_TEMP WHERE ID=V_ID;
    UNTIL DONE END REPEAT;
    CLOSE CURSOR_SQUARE;
END LAB_DEMO_SQUARE;
$$
DELIMITER ;