version: "3"
services:
    jobmanager:
        image: flink:1.14.0-scala_2.12-java11
        container_name: flink-jobmanager
        expose:
            - "6123"
        ports:
            - "8081:8081"
        command: jobmanager
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                parallelism.default: 2
    taskmanager:
        image: flink:1.14.0-scala_2.12-java11
        container_name: flink-taskmanager
        expose:
            - "6121"
            - "6122"
        command: taskmanager
        depends_on:
            - jobmanager
        links:
            - "jobmanager:jobmanager"
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                parallelism.default: 2
                taskmanager.numberOfTaskSlots: 4
                