server:
  port: 3001

spring:
  application:
    name:  rolemanager-config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:korov/ChinaGitHub.git #码云上面的git仓库名字
          search-paths: RoleManager/config-file
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAtxYX33lpZqiP+rBurm+PNU4wrc2yAWAC3vvkkX6HK3KHCoih
            8ISpqah91ZnyC2n6sCY1L/FzSz3YPLpLcEJeQxm7Ww5SPN6VYUfzhnXjxJOlC/HQ
            3u6C/sPAPqv58GDuldWE7MpJ82KXYMttBh1q4e4hvKuWd+gaaD/HIyTAv52IKLnL
            hlW5ZM8W4TexRazZG+CD/gtbFE+iAApWm03F1e1UNNOzfNqMiEq1heuOVD1613Hf
            /tcwJARWCycDUe7RWnMEZ7mDO6HplxPjabHHC3Q6p625gE5iRIz6p4OEwtkwRhFY
            IiP1mIatL/y/lQ/IhxQDm6hEM+rTTQRjMLr9okHhsO78Co5RE1WID40toPmvNhli
            Aoi39J9vT+pdOa9J/Q0YeZ9lxhwF3neou9X9x/13+Ftu0/Y1BWV4/wswjYf81893
            1qNiQgGpexlIEHB2nrQUld/gazA7XId+c0RFm+jsCfHpSn8zThnU5hlRj8tsq0eL
            bE5FLo+xOGBDS6X+mBp5XVukEUxn9unrdE7ZN6xe3jLi+5HE41EchnyIp+TAE4aN
            9vD2RT2YQoL1n8vl1RXOx0CiEYx50HgsdfW6Ex9amvQOuQ/w/PavMA+w7Vv55x01
            fpVMorKXLVS5bmbnreBWDl7W0rUfbwoL3+JB7QWA+mpNhtbklbCChfxpXhsCAwEA
            AQKCAgAOwvVBy2Q4JrcVG0yRO+VsAtXh7YfAnKEeoWiYYn87fYxtyP5ligyz5SXg
            Jv1g9jaEJVB8gRcupdnda5fRgUhgWJ7GhK0Uw01//nEgEjk/DDhuchzJHKnrKJVD
            eFI6k1YpNoH1JYo42WYjI8OyjoSjmrOVprAHEuuuJBZGOxxfVrA3uGM0fYzpF9lc
            Z0UfvQP0P3Hk9b1uMc15+1toQikFSpFTgQ4jrutNwdhI5+kd2ach38iTn33+KWtW
            ktqtrHest0FPq6FtGWzgBXZ8exz1S3W/Nz6RncBGjqdXAj+eBiziOVvFxOh0V8d2
            6wX3WsJsQazYzARTu0c2Gnh04V65p3TIUxx1R/SoPvZ1g8GshvIRz0PbwvheWOXJ
            +jzeQE0b2nHjgozZzyBo/NNcSfeTlj7LGJnZ4MvYvN26zXnQbcIJk6PWeJPHkVaY
            aqqGnuCUt/deuA0scGHElgFVH1T439g3UUwcXvG7fdn7UbHHXalFPYvDLnFX47Xw
            huAl54c/Y1Xp/KBdovMgfFXgYX0sZdCVbcwhBmFd74U0rPvfQNeF9tI3F+RtSlfF
            gVTkEBIcfUkzGHdQ8CrFNQIwKKASIkrZ8C/K0MjwSrT78uF8mFIgQa4LNXoeph5M
            Bb5EGHaUJIjRzkYu6CZ2Ki8jXSJGae1zJU2PFVd5jlKSHUaj4QKCAQEA2gFIm2vo
            S+YvXjrOoksFs160kUOojeiVBmCa0DZrlZ40upRMgyJG7s3yIWGfBcy26it0+RS2
            6pcDYeMYjwEGlofOq2T0ppJSxNnhz57vlSIGjEIhDahxqMNeSD4bCPXHBwrUBD9R
            s3FJByBf9ZI80wNembngkzAZ4kGaHorQcuNq5uTFj//dKQCh0DC0yMJxzvFc22V8
            VJF2a8rENsylYmxFsJBhUOn2hvZrt5rsK84KgvgCY9+AbU0qzNfU4acDSAV3d9cM
            J9kb2wmW6tqzWeL3sL0pPdEf0Efy7hBl1ixCztg8HLIh6++tCobTgtPubY2+Nl8H
            /cZ4KW0/64p9/wKCAQEA1v7X9MKx1vZpUFC3/hwmMaWLWbioVCRicYRk3ugvtw/F
            oX/RbN0oKjQ8UEDbcNosHjrQJ8ffrbzwu2AKw0cT2eOHmzALDSzyq/FtbfN7e9RS
            wFUi3/uudMH5m2dW18t2FAToucFXBmAJW05WrRfWAFN0RR84rkRAz6YP+TWiKuk7
            B4bFBRV2ctJVUgI5D/51Gjsn41U+x0JVBCyKjD+VXoj2B/r48E0rslE6i0li9ggR
            JK7USPkl+sFpzE371LFzVgZymWV1dDeb8PNfya9Mt+3SwHbvCt66GnaoeSdMERZH
            EN0Ny+4teapQ/FsdODREJ8A3OYR45NCm1utksUtX5QKCAQBogOUFXBznBVj/msEj
            G0OIUIXOfNh37l5ByF1uIihAeK5eImjrE6tdHmxLhDhu10t3xY01ObDVk76TVgGX
            y64UytVPY/3DO7Fhm/CbTl0a6EyrP6gInA6gD8dKajsbeHYH8jDgOFo54rxXJjXZ
            ylhN7veSSYBWDmDaDQiMS47RBCNiu5fZB5ZE6YCoBDEla9CSmzEgGu4WvARAd9rH
            SiKdo7lkglGkMAN1fvrz8Nf1x7dSQQEkTyeJPcyelXf/E8iG5df3Iqc5EuI/hcFK
            o7wGAr8pggQbFfxiI5tYc5Pdryn3bcCjIOER8LrKqQcLV/ybl67u8W8rP9CqSyyx
            BJqRAoIBAEZuypTWy6gepbW4G+7VjfWpxBMqmYqnONDzjJAyBJ+2PQqBczx031mk
            LzYjaUB5WQa2QccmhbLHOR5Jgn0i5e/1yFEg1h4E4aNOvojMwWF513pG6dvy+d4q
            RfmRSzP65b39NbjVDAt8ntQYv/CI5ITK0kZqygjdN1ZPkuAToALq0XnPvu/BbkKD
            gYwSSlthA0AKrTCelqh0pKFvbhwwIGEOAXvvzmn6/hu23LUQ36i2T9dypv0ZEkYp
            4t0ZlyzAzYYbKqPyRx5BsYaoVHMgSMPg17BRxlILUXCl+t9l7leSssllgcWTS7aW
            A14JA3OMO9/B6tWe/nQHnwC9sQkcI7kCggEBAJEiTcbvfpKYGhzDOv13x/swEAM5
            Irfv3m6KPxLUxL3BCGN6V0xNCilFF/KYlovuGRVZsWVNAVU9WHgF8SEoWprVFym7
            mrDcjTEg1qvGRsjOlHjQnj74C/EHlKLjm49YF62Ekj5eNQPAxOQa+QQTProZ0daE
            Fzt9rVvANgYrmKm6kxEokzBmcYdOlUXsWZOwfwBLTXkYyyL+nRUG0VxTUg7K7zAg
            dpdNosGBGp3/MgDG+ndUlzDmog6nGhDHCysv42UD5OP4FZSy7W5SC20andmicz3S
            KZyjSLdtgWD+yknkGSDiqxLPc8nFG6ZHzJFRSXwhrVNNFqq2sMddyxbgB4c=
            -----END RSA PRIVATE KEY-----
  rabbitmq:
    host: 192.168.106.143
    port: 5672
    username: guest
    password: guest




eureka:
  instance:
    hostname: rolemanager-config #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://192.168.106.141:7001/eureka       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      instance:
        instance-id: rolemanager-config-3001
        prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: com.korov.springcloud
  app.author: korov
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
