server:
  port: 3001

spring:
  application:
    name:  rolemanager-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/korov/ChinaGitHub.git #码云上面的git仓库名字
          search-paths: RoleManager/config-file
          clone-on-start: true
          username: korov
          password: zl7636012086
  rabbitmq:
    host: 192.168.106.143
    port: 5672
    username: guest
    password: guest




eureka:
  instance:
    hostname: rolemanager-config #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://192.168.106.141:7001/eureka       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      instance:
        instance-id: rolemanager-config-3001
        prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: com.korov.springcloud
  app.author: korov
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
