server:
  port: 3002

spring:
  application:
    name:  rolemanager-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/korov/gitee.git #码云上面的git仓库名字
          search-paths: Java/SpringCloud/RoleManager/config-file
          clone-on-start: true
          username: korov
          password: zl7636012086
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: korov-linux.com:9092  #kafka服务器的地址和端口
    consumer:
      group-id: springcloud-bus
#  rabbitmq:
#    host: 192.168.106.143
#    port: 5672
#    username: guest
#    password: guest




eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
      instance:
        instance-id: rolemanager-config-3001
        prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: com.korov.springcloud
  app.author: korov
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
