= https://zookeeper.apache.org/[Zookeeper] =
Korov9 <korov9@163.com>
v1.0 2021-3-10
:toc: right
:table-caption!:

== 使用Zookeeper ==

=== 客户端脚本 ===

进入Zookeeper的bin目录之后执行如下命令
[source,bash]
----
# 连接本地2181端口
./zkCli.sh
# 连接远程服务
./zkCli.sh -server ip:port
# 查看帮助
[zk: localhost:2181(CONNECTED) 5] help
ZooKeeper -server host:port cmd args
	addauth scheme auth
	close 
	config [-c] [-w] [-s]
	connect host:port
	create [-s] [-e] [-c] [-t ttl] path [data] [acl]
	delete [-v version] path
	deleteall path
	delquota [-n|-b] path
	get [-s] [-w] path
	getAcl [-s] path
	history 
	listquota path
	ls [-s] [-w] [-R] path
	ls2 path [watch]
	printwatches on|off
	quit 
	reconfig [-s] [-v version] [[-file path] | [-members serverID=host:port1:port2;port3[,...]*]] | [-add serverId=host:port1:port2;port3[,...]]* [-remove serverId[,...]*]
	redo cmdno
	removewatches path [-c|-d|-a] [-l]
	rmr path
	set [-s] [-v version] path data
	setAcl [-s] [-v version] [-R] path acl
	setquota -n|-b val path
	stat [-w] path
	sync path
----

==== 创建 ====

使用create创建一个Zookeeper节点用法如下：
[source,bash]
----
create [-s] [-e] path data acl
# 创建一个/zk-book的节点，节点的数据内容是123，没有任何权限控制
create /zk-book 123
----
`-s` `-e` 分别指定节点特性：顺序节点或临时节点。默认情况下不加 `-s -e` 参数的是持久节点。 `acl` 进行权限控制，缺省情况下不做任何权限控制。

==== 读取 ====

`ls` ：列出指定节点下的所有子节点，用法： `ls [-s] [-w] [-R] path` 。
[source,bash]
----
[zk: localhost:2181(CONNECTED) 2] ls /
[zk-book, zookeeper]
[zk: localhost:2181(CONNECTED) 3] ls /zk-book
[]
# ls -s 展示更详细的信息
[zk: localhost:2181(CONNECTED) 8] ls -s /zk-book
[]cZxid = 0x2
ctime = Wed Mar 10 14:42:17 UTC 2021
mZxid = 0x2
mtime = Wed Mar 10 14:42:17 UTC 2021
pZxid = 0x2
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 3
numChildren = 0
[zk: localhost:2181(CONNECTED) 20] ls -R /
/
/zk-book
/zookeeper
/zookeeper/config
/zookeeper/quota
----

`get` ：获取指定节点的数据内容和属性信息，用法： `get [-s] [-w] path`
[source,bash]
----
[zk: localhost:2181(CONNECTED) 4] get /zk-book
123
[zk: localhost:2181(CONNECTED) 21] get -s /zk-book
123
cZxid = 0x2
ctime = Wed Mar 10 14:42:17 UTC 2021
mZxid = 0x2
mtime = Wed Mar 10 14:42:17 UTC 2021
pZxid = 0x2
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 3
numChildren = 0
----

`stat` ：获取节点统计信息，用法：`stat [-w] path`
[source,bash]
----
[zk: localhost:2181(CONNECTED) 12] stat /zk-book
cZxid = 0x2
ctime = Wed Mar 10 14:42:17 UTC 2021
mZxid = 0x2
mtime = Wed Mar 10 14:42:17 UTC 2021
pZxid = 0x2
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 3
numChildren = 0
----

==== 更新 ====

`set` ：更新指定节点数据，用法： `set [-s] [-v version] path data`
[source,bash]
----
[zk: localhost:2181(CONNECTED) 1] set -s /zk-book 789
cZxid = 0x2
ctime = Wed Mar 10 14:42:17 UTC 2021
mZxid = 0x5
mtime = Wed Mar 10 15:28:59 UTC 2021
pZxid = 0x2
cversion = 0
dataVersion = 2
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 3
numChildren = 0
[zk: localhost:2181(CONNECTED) 2] get /zk-book
789
----
节点数据已经改变，并且节点中的 `dataVersion` 也改变了

==== 删除 ====

`delete` : 删除指定节点，用法： `delete [-v version] path`
[source,bash]
----
[zk: localhost:2181(CONNECTED) 4] delete /zk-book
[zk: localhost:2181(CONNECTED) 5] ls /
[zookeeper]
----

`deleteall` : 用法： `deleteall path`

==== 权限控制 ====

zookeeper通过ACL权限控制列表来控制其对znode节点的访问权限，主要的操作权限有以下5种


.权限列表
[width="100%",options="header,footer"]
|====================
|名称  |简写  |权限说明  
|CREATE  |c  |允许创建当前节点下的子节点  
|DELETE  |d  |允许删除当前节点下的子节点，仅限下一级  
|READ  |r  |允许读取节点数据以及显示子节点的列表  
|WRITE  |w  |允许设置当前节点的数据  
|ADMIN  |a  |管理员权限，允许设置或读取当前节点的权限列表  
|====================

ACL权限特点：

. zookeeper的权限是基于znode节点的，需要对每个节点设置权限
. znode节点支持同时设置多种权限方案和多个权限。当znode有多种权限的时候只要有一个权限允许当前操作，即可执行当前操作，最终权限 取多个权限之间的并集
. 子节点不会继承父节点的权限，客户端没有权限访问当前节点的时候，但是可以有权限访问当前节点的子节点
. 使用 `setAcl` 命令对节点进行权限设置会覆盖掉原来的权限

===== 相关命令 =====

添加认证用户： `addauth scheme auth`

`scheme` 权限控制模式，分为world,auth,digest,ip和super; `auth` 具体权限信息。

`addauth digest zuser:123456` :通过digest模式添加一个zuser用户，密码为123456

设置权限： `setAcl [-s] [-v version] [-R] path acl`。 `-v version` 这是权限列表的版本信息，版本不一致设置会失败。 `-R` 递归设置权限，只设置当前节点下已有的子节点的权限，新创建的节点不会继承该权限。
[source,BASH]
----
[zk: localhost:2181(CONNECTED) 4] setAcl -s -v 1 -R /zk-book auth::cdrw
[zk: localhost:2181(CONNECTED) 5] getAcl -s /zk-book
'digest,'zuser:x
: cdrw
cZxid = 0xa
ctime = Sat Mar 13 11:39:14 UTC 2021
mZxid = 0xa
mtime = Sat Mar 13 11:39:14 UTC 2021
pZxid = 0xa
cversion = 0
dataVersion = 0
aclVersion = 2
ephemeralOwner = 0x0
dataLength = 3
numChildren = 0
----

不同模式区别：

. `world` 对所有人有效( `setAcl /zk-book world:anyone:cdrw` )
. `ip` 对指定ip有效( `setAcl /zk-book ip:127.0.0.1:cdrw,ip:127.0.0.2:cdrwa` )
. `auth` 给当前会话中，权限设置之前，所有授权过的所有用户(授权之前必须在当前会话中添加授权用户，否则报错)赋予权限( `setAcl /zk-book auth::cdrw` )
. `digest` 对指定用户设置权限，需要提供用户名和密码，其中密码是明文密码进行SHA1之后再进行BASE64的编码。可以对同一个用户的不同密码设置不同的权限(通过命令加密 `echo -n zuser:123456 | openssl dgst -binary -sha1 | openssl base64` `setAcl /zk-node1 digest:zuser:cOXZibgeyYdN0OeSxQ8uPespT0g=:cdrwa` )



[NOTE]
.注意事项
====

. 一个用户可以拥有多个密码，多个密码都有效
. 认证用户添加完成之后，认证将对该会话中添加认证之后的所有操作都有效，一旦会话结束，认证失败

====

[source,BASH]
----
# 添加认证用户
addauth scheme auth
# 获取指定节点的权限列表
getAcl [-s] path
# 设置指定节点权限列表
setAcl [-s] [-v version] path acl
----



=== Java客户端API使用 ===

==== 创建会话 ====

构造方法
[source,java]
----
ZooKeeper(String connectString, int sessionTimeout, Watcher watcher)
ZooKeeper(String connectString, int sessionTimeout, Watcher watcher, boolean canBeReadOnly)
ZooKeeper(String connectString, int sessionTimeout, Watcher watcher, long sessionId, byte[] sessionPasswd)
----

. `connectString`：192.168.1.1:2181,192.168.1.2:2181
. `sessionTimeout` :会话的超时时间，毫秒为单位。Zookeeper客户端和服务器之间会通过心跳检测机制来维持会话的有效性，一旦在 `sessionTimeout` 时间内没有进行有效的心跳检测，会话就会失效
. `watcher` :事件通知处理器
. `canBeReadOnly` :在zookeeper集群中，一个机器如果和集群中过半及以上的机器失去了网络连接，那么这个机器将不再处理客户端请求。但在某些使用场景下，当zookeeper服务器发生此类故障的时候，我们还是希望zookeeper服务器能够提供读服务，此参数是否开启此功能
. `sessionId` 和 `sessionPasswd` : 代表会话的id和会话密钥，这两个参数能够唯一确定一个会话。同时客户端使用这两个参数可以实现客户端会话的复用，从而达到恢复会话的效果。

[NOTE]
.注意事项
====

zookeeper客户端和服务端会话的建立是一个异步的过程，构造方法在处理完客户端初始化工作后立即返回，在大多数情况下，此时并没有真正建立好一个会话，在会话的声明周期中处于 `CONNECTING` 的状态。当会话真正创建完毕后，zookeeper服务端会向会话对应的客户端发送一个事件通知，客户端在获取这个通知之后，才算真正建立了会话。

====

增删改查接口都有

还有一个 `zkclient` 的开源包对原有的包的功能进行了升级， `Curator` 更强的开源包

== zookeeper技术内幕 ==

=== 系统模型 ===

==== 数据模型 ====

ZNode（数据节点），ZNode是zookeeper中数据的最小单元，每个ZNode上都可以保存数据，同时还可以挂载子节点，因此构成了一个层次化的命名空间，我们称之为树

事务ID：在zookeeper中，事务是指能够改变zookeeper服务器状态的操作，我们称之为事务操作或更新操作，一般包括数据节点创建与删除、数据节点内容更新和客户端会话的创建与失效等操作。对于每一个事务请求，zookeeper都会为其分配一个全局唯一的事务id，用ZXID来表示，通常是一个64位的数字。每一个ZXID对应一次更新操作，从这些ZXID中可以间接的识别出zookeeper处理这些更新操作请求的全局顺序。

==== 节点特性 ====

. 持久节点（PERSISTENT）：数据节点被创建之后，就会一直存在于zookeeper服务器上，直到有删除操作来主动清除这个节点
. 持久顺序节点（PERSISTENT_SEQUENTIAL）：基本特性和持久节点一致，在每个父节点都会为它的第一级子节点维护一份顺序，用于记录下每个子节点创建的先后顺序。基于这个顺序特性，在创建子节点的时候，可以设置这个标记，那么在创建节点的过程中，zookeeper会自动为给定节点名加上一个数字后缀，作为一个新的、完整的节点名，数字后缀的上限是整形的最大值。
. 临时节点（EPHEMERAL）：客户端会话失效这个节点就会被自动清理掉
. 临时顺序节点（EPHEMERAL_SEQUENTIAL）：基本特性和临时节点是一致的，在此基础上添加了顺序的特性
. 容器节点（Container）：3.5.3新增的特性，没有子节点的容器节点会被清除掉
. TTL节点：3.5.3新增的特性，节点设置了失效时间，具体失效时间取决于后台检测失效线程的轮询频率

[source,bash]
----
[zk: localhost:2181(CONNECTED) 7] get -s /zk-book
null
cZxid = 0x37
ctime = Mon Mar 15 12:50:20 UTC 2021
mZxid = 0x37
mtime = Mon Mar 15 12:50:20 UTC 2021
pZxid = 0x37
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 0
numChildren = 0
----

.对象状态属性说明
[width="100%",options="header,footer"]
|====================
|状态属性  |说明  
|cZxid  |CreateZXID，表示该数据节点被创建时的事务id  
|ctime  |节点被创建的时间  
|mZxid  |ModifiedZXID，该节点最后一次被更新时的事务id  
|mtime  |最后一次被更新的时间  
|pZxid  |该节点的子节点列表最后一次被修改时的事务id，子节点列表变更才会改变此id，内容改变不会  
|cversion  |子节点版本号  
|dataVersion  |节点内容版本号  
|aclVersion  |权限列表版本号  
|ephemeralOwner  |创建该临时节点的会话的sessionID，如果该节点时持久节点，那么这个属性值为0  
|dataLength  |数据内容的长度  
|numChildren  |子节点个数  
|====================

==== 版本 ====

版本表示的时对数据节点的数据内容，子节点列表，或是节点ACL信息的修改次数。通过乐观锁的方式来确保版本一致

==== Watcher数据变更的通知 ====

zookeeper中，引入Watcher机制来实现这种分布式的通知功能。Zookeeper允许客户端向服务端注册一个Watcher监听，当服务端的一些指定事件触发了这个watcher那么就会向指定客户端发送一个事件通知来实现分布式的通知功能。

=== 序列化与协议 ===

zookeeper使用Jute这一序列化组件来进行数据的序列化和反序列化操作。







