= 从Paxos到Zookeeper分布式一致性原理与实践 =
Korov9 <korov9@163.com>
v1.0 2021-08-04
:toc: right
:table-caption!:

== 分布式架构 ==

=== 分布式的特点 ===

分布式系统的定义：分布式系统是一个硬件或软件组件分布在不同的网络计算机上，彼此之间仅仅通过消息传递进行通信和协调的系统。

一个标准的分布式系统在没有任何特定业务逻辑约束的情况下，都会有如下几个特征

- **分布性**：分布式系统中的多台计算机都会在空间上随意分布，同时，机器的分布情况也会随时变动
- **对等性**：分布式系统中的计算机没有主从之分，组成分布式系统的所有计算机节点都是对等的。副本（Replica）是分布式系统对数据和服务提供的一种冗余方式。副本分为数据副本和服务副本。数据副本是指在不同的节点上持久化同一份数据，当某一节点上存储的数据丢失时，可以从副本上读取到该数据，这是解决分布式系统数据丢失问题最有效的手段。服务副本，指多个节点提供同样的服务，每个节点都有能力接收来自外部的请求并进行相应的处理。
- **并发性**：如何准确并高效地协调分布式并发操作也成为了分布式系统架构与设计中最大的挑战之一。
- **缺乏全局时钟**：一个典型的分布式系统是由一系列在空间上随意分布的多个进程组成的，具有明显的分布性，这些进程之间通过交换信息来进行相互通信。因此在分布式系统中，很难定义两个事件究竟谁先谁后，原因就是因为分布式系统缺乏一个全局的始终序列控制。
- **故障总是会发生**：组成分布式系统的所有计算机，都有可能发生任何形式的故障。一个被大量工程实践所检验过的黄金定理是：任何在设计阶段考虑到的异常情况，一定会在系统实际运行中发生，并且，在系统实际运行过程中还会遇到很多在设计时未能考虑到的异常故障。所以除非需求指标允许，在系统设计时不能放过任何异常情况。

=== 分布式环境的各种问题 ===

==== 通信异常 ====

从集中式向分布式演变的过程中，必然引入了网络因素，网络是不可靠的。分布式系统需要在各个节点之间进行网络通信，因此每次网络通信都会伴随着网络不可用的风险。另外，即使分布式系统各节点之间的网络通信能够正常进行，其延时也会远大于单机操作。在现代计算机体系结构中，单机内存访问的延时在纳秒数量级（通常是10ns左右），而正常的一次网络通信延迟在0.1-1ms左右（相差100倍），会影响消息的收发过程，因此 **消息丢失** 和 **消息延迟** 变得非常普遍。

==== 网络分区 ====

当网络发生异常，导致分布式系统中部分节点之间的网络延时不断增大，最终导致组成分布式系统中的所有节点中，只有部分节点之间能够进行正常通信，而另一些节点则不能--这种现象称为 **网络分区** ，俗称脑裂。当网络分区出现时，分布式系统会出现局部小集群，在极端情况下，这些局部小集群会独立完成原本需要整个分布式系统才能完成的功能，包括对数据的事务处理，这就对分布式一致性提出了非常大的挑战。

==== 三态 ====

在分布式环境下，网络可能会出现各种各样的问题，因此分布式系统的每一次请求与响应，存在特有的“三态”概念，即成功、失败与超时。超时有两种情况：

- 由于网络原因，该请求并没有被成功的发送到接收方，而是在发送过程就发生了消息丢失现象；
- 该请求成功的被接收方接收后，并进行了处理，但是在将响应反馈给发送方的过程中，发生了消息丢失现象。

当发生这样的超时现象时，网络通信的发起方是无法确定当前请求是否被成功处理的。

==== 节点故障 ====

指分布式系统的服务器节点出现宕机或者僵死现象。通常根据经验来说，每个节点都有可能出现故障，并且每天都在发生。

