#Development Environment
logging:
  config: classpath:logback-dev.xml

#查看springboot开启了哪些配置
#debug: true

#只能修改内置tomcat的端口号
server:
  port: 8888

spring:
  datasource:
    name: springdatabase
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 20
    maxWait: 30000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: HTML
#    禁用缓存这样修改了页面内容，刷新页面的时候得到的是最新的页面
    cache: false
  devtools:
    restart:
      enabled: false #false，此时restart类加载器还会初始化，但不会监视文件更新
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      #exclude: WEB-INF/**

  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/


token:
  # token 加密密钥
  secret: secret
  # token 过期时间，以秒为单位，604800 是 一星期
  expiration: 604800
 
