#Production Environment
logging:
  level: org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-prod.xml

#查看springboot开启了哪些配置
debug: true

#只能修改内置tomcat的端口号
server:
  port: 80

spring:
  datasource:
    name: springdatabase
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 20
    maxWait: 30000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20